Atomizer refactor
acss-io/acss-site pull request #171
Opened 2022-07-12 23:52 UTC by redonkulus

Fixes https://github.com/acss-io/acss-site/issues/170

A ton of changes in this PR:

- Removed most references to ACSS with Atomizer, left the ACSS occurrences for Atomic CSS guides and discussions 
- Fixed the dev environment so that atomizer changes are picked up and refreshed with the jekyll changes
- Migrated all the hardcoded `<pre>...</pre>` examples to the built-in in "highlight" syntax from jekyll. Removed the old hljs syntax and css.
- Added a new subhead.html include so we can get "anchor links" for section headers

Unfortunately we do not have a preview environment so its hard to double check all the changes. Maybe I can spin up the changes on to Vercel or some static host temporarily.

2022-07-13 17:27 UTC, thierryk requested changes
There is an issue with the use of `abbr` around "Atomizer"

2022-07-13 17:27 UTC, thierryk commented on docs/assets/atomic.css
> -  *width: auto;
Why is this declaration removed?

2022-07-13 17:30 UTC, redonkulus commented on docs/_includes/footer.html
> +        <small>© 2015 - present Yahoo Inc. All rights reserved.</small>
Not for many years

2022-07-13 17:31 UTC, redonkulus commented on docs/assets/atomic.css
>    zoom: 1;
We want to remove it but it would be a breaking change so we have kept it along

2022-07-13 17:31 UTC, redonkulus commented on docs/assets/atomic.css
> -  *width: auto;
I didn't do this intentionally, just ran the build

2022-07-13 17:32 UTC, redonkulus commented on docs/_includes/header.html
> +            <abbr title="Atomized CSS" class="D(n)--xs home_D(b) Td(n) Bd(0)! Fw(b)">Atomizer <span class="Hidden">(Atomized CSS)</span></abbr>
I want to remove the ACSS as the title of the site since its not, so Atomizer is the way to go. I can clean up the abbr since its not needed anymore.

2022-07-13 17:33 UTC, carriemorrison commented on docs/assets/atomic.css
> -  *width: auto;
should we keep *hacks?

2022-07-13 17:35 UTC, redonkulus commented on docs/assets/atomic.css
> -  *width: auto;
The "ie: true," flag is set in the Gruntfile, I will remove that since we do not care about IE anymore.

2022-07-13 17:38 UTC, redonkulus commented on docs/_layouts/home.html
> +                <div class='My(10px) Fz(48px) Lh(1.2)'>Create <span class="Whs(nw)">Atomic CSS</span> <span class="Whs(nw)">with Atomizer</span></div>
It looks like this on small screens, which I think is fine:

![Screen Shot 2022-07-13 at 10 37 58 AM](https://user-images.githubusercontent.com/193272/178796142-9d41c55a-fd38-4e37-87fc-6f25e44c0451.jpg)

2022-07-13 17:42 UTC, redonkulus commented on docs/assets/atomic.css
> -  *width: auto;
Done here https://github.com/acss-io/acss-site/pull/171/commits/9f22aea96d0cee9c713ab8be830209e6e91fcc55

2022-07-13 17:43 UTC, redonkulus commented on docs/assets/atomic.css
> +  *width: auto;
With the ie option off, not sure why this is still being added, could be a bug in atomizer (cc @src-code)

2022-07-13 18:11 UTC, redonkulus commented on docs/_layouts/home.html
> +                <div class='My(10px) Fz(48px) Lh(1.2)'>Create <span class="Whs(nw)">Atomic CSS</span> <span class="Whs(nw)">with Atomizer</span></div>
Fixed the logo issue here https://github.com/acss-io/acss-site/pull/171/commits/804c88778b68ff2af1b2f44d4b8bff2af35a02f4

2022-07-13 18:11 UTC, redonkulus commented on docs/_includes/header.html
> +            <abbr title="Atomized CSS" class="D(n)--xs home_D(b) Td(n) Bd(0)! Fw(b)">Atomizer <span class="Hidden">(Atomized CSS)</span></abbr>
Cleaned up the logo here https://github.com/acss-io/acss-site/pull/171/commits/804c88778b68ff2af1b2f44d4b8bff2af35a02f4

2022-07-13 22:01 UTC, redonkulus commented
Fixed the feedback, can fix any other changes in a follow up PR.

2022-07-13 22:01 UTC, merged

2022-07-14 00:47 UTC, thierryk commented on docs/assets/atomic.css
> +  *width: auto;
Yes, I meant to remove oldIE support for the web site, not from Atomizer per se.
Also, my other comment related to the removal of a single declaration within a rule (I believe it was in the `.Row {}` ruleset) for oldIE could also be related to a bug in Atomizer as I don't see why part of the rule would be missing (cc @src-code)

2022-07-14 00:53 UTC, thierryk commented on docs/assets/atomic.css
> -  *width: auto;
Whenever this ruleset is added (`ie: true`) it should contain the 2 declarations. I do not understand how it can be added with the `*display` declaration only. May be I'm missing something...

2022-07-14 00:58 UTC, thierryk commented on docs/_includes/header.html
> +            <abbr title="Atomized CSS" class="D(n)--xs home_D(b) Td(n) Bd(0)! Fw(b)">Atomizer <span class="Hidden">(Atomized CSS)</span></abbr>
FWIW: this is **not** the title. It is nothing more than a "home" link that takes you to the "home page" and generally those links refer to the **domain name**. I'm fine with your change, I just want to point out that it will confuse some people.

2022-07-14 03:43 UTC, redonkulus commented on docs/_layouts/home.html
> +                <div class='My(10px) Fz(48px) Lh(1.2)'>Create <span class="Whs(nw)">Atomic CSS</span> <span class="Whs(nw)">with Atomizer</span></div>
Ok ya I see on homepage that its hidden always but on other pages the hamburger and icon shows up. I can take a look and fix it.

2022-07-14 15:33 UTC, redonkulus commented on docs/_layouts/home.html
> +                <div class='My(10px) Fz(48px) Lh(1.2)'>Create <span class="Whs(nw)">Atomic CSS</span> <span class="Whs(nw)">with Atomizer</span></div>
I've fixed it here https://github.com/acss-io/acss-site/commit/6bc9891133160b8692e9230edc8b1e5cb3e5ab37. There is a generic `.atomic span` rule (for React) that was overwriting my the display logic, which is why I had put the `!` in. But changing the markup to another element fixes the issue.

2022-07-14 17:35 UTC, thierryk commented on docs/_layouts/home.html
> +                <div class='My(10px) Fz(48px) Lh(1.2)'>Create <span class="Whs(nw)">Atomic CSS</span> <span class="Whs(nw)">with Atomizer</span></div>
> But changing the markup to another element fixes the issue.

A `<b>` would have been more appropriate since we are making that string bold via **`Fw(b)`** ;-)

2022-07-14 17:52 UTC, thierryk commented on docs/_layouts/home.html
> +                <div class='My(10px) Fz(48px) Lh(1.2)'>Create <span class="Whs(nw)">Atomic CSS</span> <span class="Whs(nw)">with Atomizer</span></div>
Make sure to leave the `Fw(b)`class in there as we _**reset**_ the `<b>`

2022-07-14 18:09 UTC, redonkulus commented on docs/_layouts/home.html
> +                <div class='My(10px) Fz(48px) Lh(1.2)'>Create <span class="Whs(nw)">Atomic CSS</span> <span class="Whs(nw)">with Atomizer</span></div>
Yup, already made the change in my PR to migrate all this code to the new atomizer monorepo https://github.com/acss-io/atomizer/pull/423.

This repo will be archived once the migration is completed.